### PR TITLE
Add @Postconstruct support

### PR DESCRIPTION
**Pull request by juherr**
This feature can be usefull with arities and/or main parameters. It permits to convert the string values and expose them in a better type.

### CODE REVIEW

**Comment by mkarg** [comment]
I am not convinced that such a broadly designed feature is really useful as a specific JCommander solution. Also, JCommander can be used together with cross-cutting frameworks like CDI that will provide similar solutions for post construction actions, and there should always be just one task for one tool. For JCommander, that task is parameter parsing.

For the specific example given (exposing different type) I really wonder why not parsing into that specific type right from the start?

Maybe I am missing something, so I will keep open this issue some longer to let others chime in and convince us from the actual benefit. Please chime in!

**Comment by juherr** [comment]
It was not possible to combine jcommander with an ioc framework 10 years ago 😉

I didn't find any documentation about the feature you refer. Could you share a link?

My point was: as jcommander creates the instance itself then we should be able to be notified at the end of the param injection.

As I'm not using jcommander for a while, I didn't follow its updates. Feel free to close the pr if it was covered.

**Comment by mkarg** [comment]
> I didn't find any documentation about the feature you refer. Could you share a link?

*Which* feature?

**Comment by juherr** [comment]
`JCommander can be used together with cross-cutting frameworks like CDI that will provide similar solutions for post construction actions`

**Comment by mkarg** [comment]
> > JCommander can be used together with cross-cutting frameworks like CDI that will provide similar solutions for post construction actions

You can use CDI in pure Java SE environments. CDI provides @PostConstruct to register event handlers.

**Comment by juherr** [comment]
But who calls the method and how if the instance is created by jcommander?

**Comment by juherr** [comment]
Ok, I understand. 

And it could be done by a 3rd party like https://github.com/rupert-madden-abbott/jcommander-spring-boot-starter (sadly unmaintained) for Spring Boot.

**Comment by mkarg** [comment]
@juherr Have you been able to solve your use case with the help of a third party library, or is this PR still valid?

**Comment by juherr** [comment]
Feel free to close the issue. No more a need on my side.

**Pull request closed without merging**
