### PR TITLE
Fix '--' handling

### PR DESCRIPTION
**Pull request by slonopotamus**
1. Do not fail with ArrayIndexOutOfBoundsException if '--' is the last arg
2. Do not swallow '--' that occur after '--'. This can be needed if app wants to operate on a file named '--', for example

\+ tests for both cases

Signed-off-by: Marat Radchenko marat@slonopotamus.org

### CODE REVIEW

**Comment by jeremysolarz** [comment]
@cbeust what do you say, merging?

**Comment by cbeust** [comment]
I'm ok with merging this but the conflicts need to be solved first.

**Comment by jeremysolarz** [comment]
@cbeust I hope I understood this and the other comment correct that I can merge it myself once fixed. Or shall I resolve merge conflicts and you want to do the final merge?

**Comment by cbeust** [comment]
Yup all good. thanks!

**Pull request merged**
