### PR TITLE
Remove internal collection instantiation classes

### PR DESCRIPTION
**Pull request by simon04**
Use Java 7 diamond operators instead, see Type Inference for Generic Instance Creation (https://docs.oracle.com/javase/7/docs/technotes/guides/language/type-inference-generic-instance-creation.html)

Also Guava is depreating/removing their analogous functions: https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Lists.html#newArrayList()

### CODE REVIEW

**Comment by cbeust** [comment]
I'm fine with using diamonds wherever possible but against removing the internal collections. What's the point of doing that? You're just scattering back all these collection instantiations inside the code instead of having them in one convenient location, where they can be customized if necessary.

**Comment by simon04** [comment]
I do not consider this PR overly important, so feel free to close it whenever you want.

However, I do not see any gain in having those static functions since the returned collection type is encoded in the function name (e.g., `Lists.newArrayList`); so little customization is possible. When sticking to the factory functions, one would need a factory method to obtain new `StringBuilder`, `StringKey`, … instances as well. Google Guava isn't deprecating those functions for no reason ..

**Comment by cbeust** [comment]
Yes the type is encoded in the name but in your change, the type is now encoded in the code in hundreds of places :-)

Renaming is easy, doing a search replace for all these `new` is error prone and will probably break.

Anyway, it's a nitpick. Do you know the reason why Guava is deprecating those? I still think this approach (avoiding peppering `new` in hundreds of places in your code) is valuable, especially with dependency injection being ubiquitous.

**Comment by simon04** [comment]
Concerning Guava: see google/guava@3afc6e45c39504ece02d14f4a462f65acfa98652

I guess the main intention was to get rid of the duplicated types required before Java 7 (`List<String> list = new ArrayList<String>()`).

**Pull request closed without merging**
