### PR TITLE
Fixed #532

### LINKED ISSUE #532: @-syntax not working with command objects
It seems there is a bug in the resolution of the @-syntax when command objects are used:

```java
public class BugDemo {

    public static void main(String[] args) {
        Builder builder = JCommander.newBuilder().addObject(new BugDemo()).verbose(1);
        JCommander jCommander = builder.build();
        jCommander.addCommand(new Cmd());
        jCommander.parse(args);
    }

    @Parameters(commandNames = "cmd")
    static class Cmd {

        @Parameter(names = "--foo")
        String foo;

        @Override
        public String toString() {
            return String.format("foo %s", this.foo);
        }
    }

}
```
When executed with command and options in a single line `cmd --foo X`, this works just fine.

But when executed with @-syntax `cmd @conf.txt` where `conf.txt` includes the sole line `--foo X`, this fails with a strange message: 

```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--foo X' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:961)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:762)
	at com.beust.jcommander.JCommander.parse(JCommander.java:363)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:803)
	at com.beust.jcommander.JCommander.parse(JCommander.java:363)
	at com.beust.jcommander.JCommander.parse(JCommander.java:342)
	at de.quipsy.cli.BugDemo.main(BugDemo.java:18)
```

### PR DESCRIPTION
**Pull request by mkarg**
Fixed #532

### CODE REVIEW

**Comment by mkarg** [comment]
@cbeust I don't know if it was by intention that you *enforced* the values of arguments to be on a separate line *below* the name of option, but with this change *the end user* now can opt whether to stay with the two-lines syntax *or* go with a (more intuitive) single-line syntax ("--foo X"). Would be glad if you would adopt my change proposal. :-)

**Comment by mkarg** [comment]
Looking at what my PR currently does, it might be better to change the regex in a way that allows to limit the line split to a *single* one, so the *value* actually can contain blanks, like this:
`--foo bar baz`
(which aligns with the possibility of the *inline* argument `--foo "bar baz"`).
For example, just apply the split "just once", not "for each".
Or we could actually check the quotes, just like the command line does?
WDYT?

**Comment by cbeust** [comment]
Would you mind adding a test?

**Comment by mkarg** [comment]
I would be glad to add a test, but we should first clarify the behavior it shall assert: Do we want the solution as-is (i. e. truncate at EACH blank) or do we instead want to "truncate at FIRST blank"?

**Comment by mkarg** [comment]
@cbeust Initial test "as-is" can be found in https://github.com/cbeust/jcommander/pull/533/commits/eee072ab324206ea6089676aad55b60fe3aba6cc. If we agree upon blank handling within values, I will modify it.

**Pull request merged**
