### PR TITLE
Fields annotated with @ParametersDelegate are now allowed to be final.

### PR DESCRIPTION
**Pull request by tfiskgul**
The final check should not apply to these fields.

### CODE REVIEW

**Comment by tfiskgul** [comment]
Hi @cbeust , is my reasoning correct regarding the @ParametersDelegate annotated field?

**Comment by tfiskgul** [comment]
Hi, @cbeust, please consider giving this some feedback, JCommander is a great project, and I would like to see it thrive =)

**Comment by jeremysolarz** [comment]
@cbeust any input on that?

**Comment by cbeust** [comment]
You're welcome to merge this after fixing the conflicts.

**Pull request merged**
