### PR TITLE
Moved the 'module-info.java' file to src/main/java to support Java 9

### PR DESCRIPTION
**Pull request by szediwy**
Moved back module-info.java to support Java 9 JLink,

### CODE REVIEW

**Comment by cbeust** [comment]
Are you able to build at all with this change? I get:

```
$ ./gradlew assemble

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

```

**Comment by szediwy** [comment]
`javac:` invalid source release: 1.10`

**Comment by szediwy** [comment]
It looks like there are some issue of kobalt together with Oracle JDK 10:
`***** ERROR Couldn't compile file: java.lang.ArrayIndexOutOfBoundsException: 450
	at org.jetbrains.org.objectweb.asm.ClassReader.readUnsignedShort(ClassReader.java:2464)
	at org.jetbrains.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2525)
	at org.jetbrains.org.objectweb.asm.ClassReader.readModule(ClassReader.java:761)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:646)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:507)
	at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:67)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.findSystemModule(CliJavaModuleFinder.kt:44)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.access$findSystemModule(CliJavaModuleFinder.kt:25)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:25)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:254)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.none(_Sequences.kt:1258)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:227)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:223)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:401)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:282)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createEnvironmentWithScriptingSupport(K2JVMCompiler.kt:272)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:192)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:61)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1$invokeCompilerDirectly$duration$1.invoke(KotlinCompiler.kt:261)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1$invokeCompilerDirectly$duration$1.invoke(KotlinCompiler.kt:43)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.invokeCompilerDirectly(KotlinCompiler.kt:260)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:99)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:36)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:428)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:454)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile$default(KotlinCompiler.kt:451)
	at com.beust.kobalt.app.BuildFileCompiler.maybeCompileBuildFile(BuildFileCompiler.kt:165)
	at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:114)
	at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:73)
	at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles$default(BuildFileCompiler.kt:47)
	at com.beust.kobalt.app.ProjectFinder.initForBuildFile(ProjectFinder.kt:20)
	at com.beust.kobalt.Options.run(Options.kt:59)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:136)
	at com.beust.kobalt.Main.run(Main.kt:117)
	at com.beust.kobalt.Main$Companion.launchMain(Main.kt:71)
	at com.beust.kobalt.Main$Companion.mainNoExit(Main.kt:50)
	at com.beust.kobalt.MainKt.main(Main.kt:20)`

**Comment by szediwy** [comment]
./gradlew assemble did work though.

**Comment by mkarg** [comment]
@szediwy Apparently the source branch does not exists anymore. If you still think that your contribution should get integrated into JCommander then please reopen this PR. Until then, I do close this PR for better overview. Thank you for contributing to JCommander!

**Pull request closed without merging**
