### PR TITLE
GH-477 Environment Variable Default Provider

### LINKED ISSUE #477: Question: Environment Variable with Default Parameters
Is there a possibility to use Environment Variables with default parameters? The idea is to have MYTOOL_OPTS="-x 1 -y 2 -z 3" in the environment and JCommander will apply these in case "-x", "-y", "-z" are not supplied explicitly on the command line.

I tried to do that with existing JCommander means but did not find a way to make it work.

### PR DESCRIPTION
**Pull request by mkarg**
Closes #477

### CODE REVIEW

**Comment by mkarg** [comment]
@cbeust WDYT? :-)

**Comment by mkarg** [comment]
@cbeust I would kindly like to ask you for a review of this contribution. :-)

**Comment by cbeust** [comment]
Looks good to me! Let me know when this PR is no longer a work in progress and I'll merge it.

Thanks!

**Comment by mkarg** [comment]
> Looks good to me! Let me know when this PR is no longer a work in progress and I'll merge it.

All tests passing now, PR is no more a work in progress, would be happy if you merge it! :-)

**Comment by mkarg** [comment]
@cbeust Thanks for merging! :-)

**Pull request merged**
