### PR TITLE
Added converters for URIs, URLs and Paths

### PR DESCRIPTION
**Pull request by samvv**
Tests might need to be provided (not sure they work)

### CODE REVIEW

**Comment by nikolavp** [comment]
Why was this closed? If there aren't any plans on incorporating those converters for let's say code size issue, it might be a good idea to provide converters as part of another project?

**Comment by cbeust** [comment]
Hi Sam,

Sorry, I should have explained.

I'm just trying to keep the core as simple as possible and I haven't seen a
lot of demand for this. It's also so trivial that anyone who needs this can
write such a class in thirty seconds...



-- 
Cédric

**Comment by garydgregory** [comment]
Every time a write a program that uses JCommander, I have to hunt around for my little pile of converts, it's a pain. URL and URI are basic JRE types, they should be supported out of the box IMO.

**Comment by garydgregory** [comment]
Oh, and I do have one for Path as well... just like the user above.

**Comment by TKlerx** [comment]
I would also have these standard converters. Why do you supply a File-Converter but not a Path-Converter? In every project I have to not just import JCommander but also some custom converters...
Would really appreciate converters for basic JRE types.

(I wrote this in this closed issue cause I did not want to open a new issue.)

**Comment by garydgregory** [comment]
+1

Gary

On Wed, Mar 11, 2015 at 6:57 AM, TKlerx <notifications@github.com> wrote:

> I would also have these standard converters. Why do you supply a
> File-Converter but not a Path-Converter? In every project I have to not
> just import JCommander but also some custom converters...
> Would really appreciate converters for basic JRE types.
>
> (I wrote this in this closed issue cause I did not want to open a new
> issue.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/jcommander/pull/189#issuecomment-78267130>.
>



-- 
E-Mail: garydgregory@gmail.com | ggregory@apache.org
Java Persistence with Hibernate, Second Edition
<http://www.manning.com/bauer3/>
JUnit in Action, Second Edition <http://www.manning.com/tahchiev/>
Spring Batch in Action <http://www.manning.com/templier/>
Blog: http://garygregory.wordpress.com
Home: http://garygregory.com/
Tweet! http://twitter.com/GaryGregory

**Comment by cbeust** [comment]
Alright you convinced me, I'll merge it.

**Comment by garydgregory** [comment]
Nice. When can we expect a new release?

Interested in converters for Charset and ByteOrder?

Gary

On Wed, Mar 11, 2015 at 9:02 AM, Cedric Beust <notifications@github.com>
wrote:

> Merged #189 <https://github.com/cbeust/jcommander/pull/189>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/jcommander/pull/189#event-250209330>.
>



-- 
E-Mail: garydgregory@gmail.com | ggregory@apache.org
Java Persistence with Hibernate, Second Edition
<http://www.manning.com/bauer3/>
JUnit in Action, Second Edition <http://www.manning.com/tahchiev/>
Spring Batch in Action <http://www.manning.com/templier/>
Blog: http://garygregory.wordpress.com
Home: http://garygregory.com/
Tweet! http://twitter.com/GaryGregory

**Comment by TKlerx** [comment]
I also changed the DefaultConverterFactory.java
Do I have to open an new Pullrequest for this? It is located here:
https://github.com/TKlerx/jcommander

**Comment by cbeust** [comment]
Yes please.

-- 
Cédric

**Pull request merged**
