### PR TITLE
Implementation for issue https://github.com/cbeust/jcommander/issues/395

### PR DESCRIPTION
**Pull request by dibog**
Hi,

in the following pull request you can find my implementation for the feature I described within issue https://github.com/cbeust/jcommander/issues/395.

It contains:
- the change it self
- test cases  (as I'm unfamilier with TestNG they might be not fully correct)
- I added to your documentation, but as I'm not familar with gradle or koblat I couldn't check it (I'm using maven)

Best regards,
Dieter

### CODE REVIEW

**Comment by dibog** [comment]
I'm working on a windows system and there I couldn't get the project to run or test run as I'm no aware how to do that with Unix only scripts.
My test class run fine within IntelliJ though. The errors which occured seems not to stem from my changes, but from a defect configuration.
If a pom would be provided I could check what exactly went wrong.

**Comment by mkarg** [comment]
Are you still interested in this contribution?

**Comment by mkarg** [comment]
@dibog Kindly requesting your response! :-)

**Comment by dibog** [comment]
@mkarg Hi Markus, 

since some years I switch to Kotlin and am using there the very nice https://ajalt.github.io/clikt/.
So I have no more interest in this change request, but in case you want to use my merge request, feel free to use it.

Best regards,
Dieter

**Comment by mkarg** [comment]
Thank you for your quick answer, Dieter. In fact I do not see the benefit of `valueOf` for the reason outlined in https://github.com/cbeust/jcommander/issues/395#issuecomment-337334608. Anyways, thank you for contributing to JCommander. :-)

**Pull request closed without merging**
