### PR TITLE
Add a hint about mutually exclusive parameters

### LINKED ISSUE #272: Document mutually exclusive parameters
Hi!
Firstofall thanks for your great framework. It's so cool and easy to use! 👍 
I'd like to suggest that you add a short hint to the documentation about mutually exclusive parameters. Now I read #41 and understand your reasoning as it's really not a problem to implement it by oneself.

Still I was about to open an issue about this and others are likely to search for this as well.

### PR DESCRIPTION
**Pull request by wedi**
Closes #272

### CODE REVIEW

**Comment by wedi** [comment]
The failed checks are not due to my changes. As far as I understand the test system initialization fails.

**Comment by cbeust** [comment]
@wedi Yes, your change didn't cause the failure, don't worry about it.

As for your change, I think I'd rather phrase it in a more general way and explain why JCommander doesn't perform any validation (not just validating mutually exclusive parameters).

**Comment by cbeust** [comment]
Done:  http://jcommander.org/#Parameter_validation

**Comment by wedi** [comment]
Ok. That is of course absolutely fine for me. I'm not a native speaker anyway. I just wanted to keep it simple for you.

**Pull request closed without merging**
